spring:
  # --- PostgreSQL Database Configuration ---
  datasource:
    url: jdbc:pgsql://localhost:5432/jibmeak_qa_db
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  # --- We disable the H2 console ---
  h2:
    console:
      enabled: false

  # --- JPA/Hibernate Settings for PGSQL ---
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop