spring.config.import: "optional:dotenv:.env"

# OCP/Strategy switch
app:
  optimizer:
    active : "ai"
  ai:
    provider: "openai"

spring:
  profiles:
    active: "dev"

  # --- Common Settings ---
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # --- AI CONFIGURATIONS ---
  ai:
    # --- OpenAI Configuration ---
    openai:
      enabled: ${app.ai.provider:openai, "none"} == "openai"
      api-key: "${SPRING_AI_OPENAI_API_KEY}"

    # --- Google Gemini Configuration ---
    google:
      genai:
        enabled: ${app.ai.provider:gemini, "none"} == "gemini"
        api-key: "${SPRING_AI_GEMINI_API_KEY}"
