spring:
  # --- PostgreSQL Database Configuration ---
  datasource:
    url: jdbc:pgsql://localhost:3306/jibmeak_qa_db
    username: postgres
    password:
    driver-class-name: com.pgsql.cj.jdbc.Driver

  # --- We disable the H2 console ---
  h2:
    console:
      enabled: false

  # --- JPA/Hibernate Settings for MySQL ---
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect