spring:
  profiles:
    active: "dev"

  # --- Common Settings ---
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Spring AI Config
  ai:
    openai:
      api-key: "${SPRING_AI_OPENAI_API_KEY}"

  # set up the OCP/Strategy switch here
  app:
    optimizer:
      active : ""